// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Article struct {
	ID          uuid.UUID
	Sourceid    uuid.UUID
	Tags        string
	Title       string
	Url         string
	Pubdate     time.Time
	Video       sql.NullString
	Videoheight int32
	Videowidth  int32
	Thumbnail   string
	Description string
	Authorname  sql.NullString
	Authorimage sql.NullString
}

type Discordqueue struct {
	ID        uuid.UUID
	Articleid uuid.UUID
}

type Discordwebhook struct {
	ID      uuid.UUID
	Name    sql.NullString
	Key     sql.NullString
	Url     sql.NullString
	Server  sql.NullString
	Channel sql.NullString
	Enabled sql.NullBool
}

type Icon struct {
	ID       uuid.UUID
	Filename sql.NullString
	Site     sql.NullString
}

type Setting struct {
	ID      uuid.UUID
	Key     string
	Value   string
	Options sql.NullString
}

type Source struct {
	ID      uuid.UUID
	Site    sql.NullString
	Name    sql.NullString
	Source  sql.NullString
	Type    sql.NullString
	Value   sql.NullString
	Enabled sql.NullBool
	Url     sql.NullString
	Tags    sql.NullString
}
