// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Article struct {
	ID          uuid.UUID
	Sourceid    uuid.UUID
	Tags        sql.NullString
	Title       sql.NullString
	Url         sql.NullString
	Pubdate     sql.NullTime
	Video       sql.NullString
	Videoheight sql.NullInt32
	Videowidth  sql.NullInt32
	Thumbnail   sql.NullString
	Description sql.NullString
	Authorname  sql.NullString
	Authorimage sql.NullString
}

type Discordqueue struct {
	ID        uuid.UUID
	Articleid uuid.UUID
}

type Discordwebhook struct {
	ID      uuid.UUID
	Name    sql.NullString
	Key     sql.NullString
	Url     sql.NullString
	Server  sql.NullString
	Channel sql.NullString
	Enabled interface{}
}

type Icon struct {
	ID       uuid.UUID
	Filename sql.NullString
	Site     sql.NullString
}

type Setting struct {
	ID      uuid.UUID
	Key     string
	Value   string
	Options sql.NullString
}

type Source struct {
	ID      uuid.UUID
	Site    sql.NullString
	Name    sql.NullString
	Source  sql.NullString
	Type    sql.NullString
	Value   sql.NullString
	Enabled interface{}
	Url     sql.NullString
	Tags    sql.NullString
}
