basePath: /api
info:
  contact: {}
  title: NewsBot collector
  version: "0.1"
paths:
  /config/articles:
    get:
      produces:
      - application/json
      responses: {}
      summary: Lists the top 50 records
      tags:
      - config
      - articles
  /config/articles/{id}:
    get:
      parameters:
      - description: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Returns an article based on defined ID.
      tags:
      - config
      - articles
  /config/sources:
    get:
      produces:
      - application/json
      responses: {}
      summary: Lists the top 50 records
      tags:
      - config
      - source
  /config/sources/{id}:
    delete:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses: {}
      summary: Deletes a record by ID.
      tags:
      - config
      - source
    get:
      parameters:
      - description: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Returns a single entity by ID
      tags:
      - config
      - source
  /config/sources/{id}/disable:
    post:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses: {}
      summary: Disables a source from processing.
      tags:
      - config
      - source
  /config/sources/{id}/enable:
    post:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses: {}
      summary: Enables a source to continue processing.
      tags:
      - config
      - source
  /config/sources/new/reddit:
    post:
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      - description: url
        in: query
        name: url
        required: true
        type: string
      responses: {}
      summary: Creates a new reddit source to monitor.
      tags:
      - config
      - source
      - reddit
  /config/sources/new/twitch:
    post:
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      - description: url
        in: query
        name: url
        required: true
        type: string
      - description: tags
        in: query
        name: tags
        required: true
        type: string
      responses: {}
      summary: Creates a new twitch source to monitor.
      tags:
      - config
      - source
      - twitch
  /config/sources/new/youtube:
    post:
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      - description: url
        in: query
        name: url
        required: true
        type: string
      - description: tags
        in: query
        name: tags
        required: true
        type: string
      responses: {}
      summary: Creates a new youtube source to monitor.
      tags:
      - config
      - source
      - youtube
  /hello/{who}:
    get:
      parameters:
      - description: Who
        in: path
        name: who
        required: true
        type: string
      produces:
      - text/plain
      responses: {}
      summary: Responds back with "Hello x" depending on param passed in.
      tags:
      - debug
  /helloworld:
    get:
      produces:
      - text/plain
      responses: {}
      summary: Responds back with "Hello world!"
      tags:
      - debug
  /ping:
    get:
      produces:
      - text/plain
      responses: {}
      summary: Sends back "pong".  Good to test with.
      tags:
      - debug
swagger: "2.0"
